export interface Candidate {
    id: string;
    fullName: string;
    position: string;
    status: 'Not Interviewed' | 'Passed' | 'Rejected' | 'Maybe';
    experience: {
        years: number;
        months: number;
    };
    interviewDate?: string; // ISO string format for the interview date
    questions: Question[];
    resume?: any; // Parsed JSON resume object generated by AI
    jobDescription?: JobDescription; // Job Description object
    jdMatchPercentage?: number; // JD Match percentage (0-100)
    createdAt: string;
}

export interface Question {
    id: string;
    text: string;
    section: string;
    answer?: string;
    isCorrect?: boolean;
    isAnswered: boolean;
}

export interface InterviewResult {
    id: string;
    candidateId: string;
    description: string;
    result: 'Passed' | 'Rejected' | 'Maybe';
    questions: Question[];
    createdAt: string;
}

export interface QuestionSection {
    id: string;
    name: string;
    questions: Question[];
}

export interface QuestionTemplate {
    id: string;
    name: string;
    sections: QuestionSection[];
}

export interface JobDescription {
    id: string;
    title: string;
    description: string;
    createdAt: string;
}

export interface AppState {
    candidates: Candidate[];
    questionTemplates: QuestionTemplate[];
    positions: string[];
    jobDescriptions: JobDescription[];
}

// New interfaces for complete backup and export
export interface ThemeSettings {
    theme: 'light' | 'dark';
    primaryColor: 'blue' | 'teal' | 'purple' | 'indigo' | 'orange';
}

export interface AISettings {
    apiKey?: string;
    geminiApiKey?: string;
    geminiConnected?: boolean;
}

export interface CompleteAppData {
    candidates: Candidate[];
    questionTemplates: QuestionTemplate[];
    positions: string[];
    jobDescriptions: JobDescription[];
    interviewResults: InterviewResult[];
    themeSettings: ThemeSettings;
    aiSettings: AISettings;
    localStorageData: Record<string, any>; // For any other localStorage items
    exportedAt: string;
    version: string;
} 